In [92]:
import numpy as np
from overall import Data
n_cuts = 3
n_settings = n_cuts ** 8

ds = Data()
j = np.arange(n_cuts)
ranges = ds.means_sig+(j * (ds.means_bckg[:,np.newaxis] - ds.means_sig[:,np.newaxis]) / n_cuts).T

settings = np.zeros((n_settings,8))

test = np.zeros((n_settings,8),dtype=int)

for k in range(n_settings):
    div = 1
    set = np.zeros(8)
    for i in range(8):
        idx = (k // div) % n_cuts
        set[i] = ranges[idx,i]
        div *= n_cuts
        test[k,i] = idx
    settings[k,:] = set

settings = np.zeros((n_settings,8))
div = n_cuts**np.arange(8)
k = np.arange(n_settings)
idx = (k[:,np.newaxis]) // div % n_cuts
i = np.arange(8)
settings = ranges[idx,i]

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [2 1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [1 2 0 0 0 0 0 0]]
[[ 3.89250239e+01  6.77555732e-03  5.07776798e-03  4.18748906e-01
   1.95532275e+00 -8.67511218e-01 -1.10022287e-05  1.24596383e-02]
 [ 4.13766506e+01  5.99300700e-02  3.77865490e-02  4.43590891e-01
   3.45779819e+00 -6.29694591e-01  2.08235447e-06  1.24927844e-02]
 [ 4.38282774e+01  1.13084583e-01  7.04953300e-02  4.68432876e-01
   4.96027363e+00 -3.91877963e-01  1.51669376e-05  1.25259305e-02]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[ 4.13766506e+01  6.77555732e-03  5.07776798e-03  4.18748906e-01
  1.95532275e+00 -8.67511218e-01 -1.10022287e-05  1.24596383e-02]
